import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
  AppBar,
  Button,
  Paper,
  Card,
  Grid,
  ThemeProvider,
  Toolbar,
  Typography,
} from "@mui/material";
import { themeOptions } from "../material_theme";
import { useTheme } from "@mui/styles";

import useStyles from "./styles";
import { ArrowRight } from "@mui/icons-material";
import MarketDisplay from "../components/MarketDisplay/MarketDisplay";
import Ticker from 'react-ticker'
import Footer from "../components/Footer/Footer";
const MARKETS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
const BUTTONS = ['Exchange', 'Markets', 'Payouts', 'DAO'];

export default function Home() {
  const classes = useStyles();
  const theme = useTheme();

  return (
    <ThemeProvider theme={themeOptions}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons"
          />
        </Head>

        <main className={styles.main}>
          {/* Introduction Section */}
          <section className={classes.introductionSection}>

            <Paper
            className={classes.appbarPaper}
              square={true}
              classes={{ outlined: classes.appbar }}
              elevation={0}
              variant='outlined'
            >
                <Grid container direction='row' justifyContent='space-between' alignItems='center'>
                    <Grid item>
                      <Typography variant='h6'>
                        Opportunity
                      </Typography>
                    </Grid>

                    <Grid item>
                        <Grid container item direction='row' alignItems='center'>
                          <Typography px={1}> 
                            Blog
                          </Typography>

                          <Typography px={1}>
                            FAQ
                          </Typography>

                          <Typography px={1}>
                            Contributions
                          </Typography>
                        </Grid>
                    </Grid>

                    <Grid item>
                        <Button variant='outlined' color='secondary'>
                          Go to Application
                        </Button>
                    </Grid>
                </Grid>
            </Paper>
            <Grid
              className={classes.introductionSectionGrid}
              container
              wrap='wrap'
              direction="column"
              alignItems="center"
              justifyContent="space-evenly"
            >
                        <div className={classes.backgroundImageContainer}>
              <img className={classes.backgroundImage} src='/world.png' />
            </div>

              <Grid item>
                <div className={classes.introductionTextContainer}>
                  <Typography
                    py={2}
                    variant="h1"
                    textAlign="center"
                    fontSize={40}
                    color="rgba(33, 33, 33, .85)"
                    fontWeight="bold"
                  >
                    Making money shouldn't be a <span style={{ color: 'rgba(102, 197, 107, .85)' }} fontWeight="bold" variant="h1" fontSize={40}>privilege</span>
                  </Typography>
                  <Typography
                    width="70%"
                    variant="subtitle2"
                    textAlign="center"
                    fontSize={25}
                    color="rgba(33, 33, 33, .85)"
                    fontWeight="light"
                  >
                    No forms or unecessary documentation. Connect a wallet and
                    work. It's just that simple.
                  </Typography>
                </div>
              </Grid>

              <Grid item>
                <Button
                  p={10}
                  variant="outlined"
                  className={classes.introductionChatButton}
                  endIcon={<ArrowRight />}
                >
                  Chat with us on Discord
                </Button>
              </Grid>

              <Grid item style={{width: '100vw'}}>
                
                <marquee style={{width: '100vw'}} width='100vw' direction='left' loop>
                {
                  MARKETS.map(market => { return <MarketDisplay /> })
                }
                        
                </marquee>
              </Grid>
            </Grid>
          </section>


          {/* Section 2 */}
          <section className={classes.section}>
              <Grid container direction='row' alignItems='center' justifyContent='space-between'>
                <Grid item flexGrow={0.5}>
                  <>
                    <Card elevation={1} style={{width: '400px', height: '160px', margin: '15px 0px' }}>
                    <img src='/crosswalk.jpeg' style={{width: '100%', height: '100%'}} />
                    </Card>

                    <Card elevation={1} style={{width: '400px', height: '160px', margin: '15px 0px' }}>
                    <img src='/crosswalk.jpeg' style={{width: '100%', height: '100%'}} />
                    </Card>

                  </>
                </Grid>

                <Grid item style={{width: '40%'}}>
                  <Typography py={2} fontSize={20} color='rgba(102, 197, 107, .85)'>
                    Earn money with no hassle
                  </Typography>

                  <Typography py={2} fontSize={30} fontWeight='medium' color='rgba(33, 33, 33, 0.85)'>
                    The ability to work made easy
                  </Typography>

                  <Typography py={2} fontSize={18} fontWeight='light'>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et commodo ligula. Fusce orci erat, aliquet sit amet est quis, auctor dictum orci.
                  </Typography>

                </Grid>
              </Grid>
          </section>

          {/* Section 3 */}
          <section className={classes.section}>
              <Grid container direction='row' alignItems='center' justifyContent='space-between'>

                <Grid item style={{width: '40%'}}>
                  <Typography py={2} fontSize={20} color='rgba(102, 197, 107, .85)'>
                    Made for individuals
                  </Typography>

                  <Typography py={2} fontSize={30} fontWeight='medium' color='rgba(33, 33, 33, 0.85)'>
                    No corporations, just people
                  </Typography>

                  <Typography py={2} fontSize={18} fontWeight='light'>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et commodo ligula. Fusce orci erat, aliquet sit amet est quis, auctor dictum orci.
                  </Typography>

                </Grid>

                <Grid item flexGrow={0.5}>
                    <Card elevation={1} style={{width: '100%', height: '200px', margin: '15px 0px' }}>
                    <img src='/boy_staring.jpeg' style={{width: '100%', height: '100%'}} />
                    </Card>
                </Grid>
              </Grid>
          </section>

          <section className={classes.section}>
            <Grid container alignItems='center' justifyContent='center'>
            <Card elevation={1} style={{ position: 'relative', width: '100%', height: '600px', margin: '15px 0px' }}>
            <div className={classes.shadowyDiv} style={{display: 'flex', alignItems: 'center', justifyContent: 'center', width: '100%', height: '600px'}}>
              <Typography color='#fff' variant='h6' fontSize={40}>
                The ability to work is now in the hands of everyone.
              </Typography>
            </div>
            <img src='/crowd.jpeg' style={{width: '100%', height: '100%'}} />
            
            </Card>
            
             
            </Grid>
          </section>

          {/* Section 4 */}
          <section className={classes.section}>

          </section>


          {/* Section 5 */}
          <section className={classes.section}>
            <Grid container alignItems='center' justifyContent='center'>
            <Card elevation={1} style={{ position: 'relative', width: '100%', height: '300px', margin: '15px 0px' }}>
            <div className={classes.shadowyDiv} style={{display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'space-evenly', width: '100%', height: '300px'}}>
              <Typography color='#fff' fontWeight='medium' fontSize={20}>
              Accessible to anyone
              </Typography>

              <Typography color='#fff' fontWeight='regular' fontSize={18}>
              Global access to freelancers and employers. No bank accounts, licenses or agreements necessary.
              </Typography>

              <Typography color='#fff' fontWeight='regular' fontSize={18}>
              Start earning money today with just a few clicks.
              </Typography>
            </div>
            <img src='/freelance_woman_one.png' style={{width: '100%', height: '100%'}} />
            </Card>
            </Grid>
          </section>

          {/* Section 6 */}
          <section  className={classes.centeredSection}>
            <div>
              <Typography textAlign='center' fontWeight='medium' fontSize={30}>
                Learn Opportunity
              </Typography>
              <Typography textAlign='center' fontWeight='regular' fontSize={25}>
              Creating a secure protocol for permissionless work
              </Typography>
            </div>
            
            <Grid my={6} container direction='row' alignItems='center' justifyContent='space-evenly'>
              {
                BUTTONS.map(button => {
                  return <Button variant='text'> {button} </Button>
                })
              }
            </Grid>

            <Typography style={{width: '1010px' }} component='p' textAlign='center'>
            Maecenas sagittis elit eu odio elementum, in malesuada felis dictum. Fusce pulvinar odio turpis, rhoncus sagittis eros aliquam vel. Nullam ut tristique ante. Aenean ullamcorper diam a finibus vestibulum. Vestibulum tortor nunc, tempor vel nisi at, faucibus pretium ligula. Pellentesque et justo lobortis, convallis sem eget, pharetra orci. Ut tempor finibus efficitur. 
            </Typography>
          </section>

          {/* Section 7*/}
          <section className={classes.section}>
            <Grid container alignItems='center' justifyContent='center'>
            <Card elevation={1} style={{ position: 'relative', width: '100%', height: '600px', margin: '15px 0px' }}>
            <div className={classes.shadowyDiv} style={{padding: '5% 7%', display: 'flex', flexDirection: 'column', alignItems: 'flex-start', justifyContent: 'center', width: '100%', height: '600px'}}>
              <Typography py={3} color='#fff' variant='h6' fontSize={40}>
              The future of work relies on highly skilled individuals, not corporations.
              </Typography>
              <Button variant='outlined' color='secondary'>
                Learn more
              </Button>
            </div>
            <img src='/freelance.jpg' style={{width: '100%', height: '100%'}} />
            
            </Card>
            
             
            </Grid>
          </section>

          <Footer />
   
          
        </main>
      </div>
    </ThemeProvider>
  );
}
